name: CI

# Aside from just this yml, you also need to enable 
# CodeQL and Secrets scanning in the repository settings 
# in GitHub. 

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

# CI should not need to modify the repository.
permissions:
  contents: read

jobs:
  test:
    name: Test Python ${{ matrix.python-version }}
    runs-on: windows-latest

    strategy:
      fail-fast: false
      matrix:
        python-version:
          - "3.10"
          - "3.11"
          - "3.12"
          - "3.13"
          - "3.14"

    steps:
      - name: Check out repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7.0.1

      - name: Set up Python
        uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97  # v7.0.0
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install uv
        uses: astral-sh/setup-uv@20cfd1bf945f4377ade1205e4dbc17946fc9a30d # v10.0.1
        with:
          version-file: uv.lock
        
      - name: Install packages
        run: |
          uv sync --locked --group dev

      - name: Lint
        run: |
          uv run ruff check .

      - name: Check formatting
        run: |
          uv run ruff format --check .

      - name: Audit dependencies
        run: |
          uv run pip-audit --local

      - name: Test
        run: |
          uv run pytest -v --durations=2